# Generated by Django 3.1.1 on 2020-09-25 10:19

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('sdms_app', '0003_auto_20200925_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='sdms_app.TaggedStudent', to='sdms_app.StudentTag', verbose_name='Tags'),
        ),
    ]
